Linking to GEOS 3.6.2, GDAL 2.2.1, PROJ 4.9.3

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.2     ✔ purrr   0.3.4
✔ tibble  3.0.3     ✔ stringr 1.4.0
✔ tidyr   1.1.0     ✔ forcats 0.5.0
✔ readr   1.3.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
Linking to liblwgeom 3.0.0beta1 r16016, GEOS 3.6.2, PROJ 4.9.3
Error: Problem with `filter()` input `..1`.
✖ object 'GMBA_V2_ID' not found
ℹ Input `..1` is `GMBA_V2_ID == domain`.
Backtrace:
     █
  1. ├─gmba_kba %>% filter(GMBA_V2_ID == domain)
  2. ├─dplyr::filter(., GMBA_V2_ID == domain)
  3. ├─sf:::filter.sf(., GMBA_V2_ID == domain)
  4. │ └─sf:::.re_sf(...)
  5. │   └─base::stopifnot(...)
  6. ├─base::NextMethod()
  7. ├─dplyr:::filter.data.frame(., GMBA_V2_ID == domain)
  8. │ └─dplyr:::filter_rows(.data, ...)
  9. │   ├─base::withCallingHandlers(...)
 10. │   └─mask$eval_all_filter(dots, env_filter)
 11. └─base::.handleSimpleError(...)
 12.   └─dplyr:::h(simpleError(msg, call))
Execution halted
